### PR TITLE
add zh_tw

### PR DESCRIPTION
**Pull request by zackzheng1121**
Resolves 

## Submitter Checklist:

- [ ] There is a [ticket](https://github.com/meetrevision/revision-tool/issues) for my issue
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Discussed about the issue with reviewers in Discussions, Issues or other platforms 
- [x] Confirmed that the PR only includes changes related to my issue
- [ ] Checked the PR locally: `flutter build windows` (Request it to reviewers if you're having problems)

### CODE REVIEW

**Comment by justrainer** [comment]
checked the translations with google translate, everything seems to be fine.

**Comment by zackzheng1121** [comment]
等等，我太著急了，忘了構建

**Comment by justrainer** [comment]
I think you need to adjust additional files to make the language appear with the other options. Refer to this PR as a reference what needs to be done: https://github.com/meetrevision/revision-tool/pull/34/files

**Comment by zackzheng1121** [comment]
how to do?

**Comment by melo936** [comment]
Thanks for contributing

**Comment by zackzheng1121** [comment]
If you need translation, you can private message my discord 🙏

h3r0 ***@***.***> 於 2023年8月30日 週三 16:58 寫道：

**Pull request merged**
